/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  ComputerBasic:[
    {
      type:'autogenerated',
      dirName: 'computer-basic'
    }
  ],
  FrontEnd:[
    {
      type:'autogenerated',
      dirName:'front-end'
    }
  ],
  BackEnd:[
    {
      type:'autogenerated',
      dirName:'back-end'
    }
  ],
  AI:[
    {
      type:'autogenerated',
      dirName:'AI'
    }
  ],
  English:[
    {
      type:'autogenerated',
      dirName:'english'
    }
  ],
  Math:[
    {
      type:'autogenerated',
      dirName:'math'
    }
  ],
  Framework:[
    {
      type:'autogenerated',
      dirName:'framework'
    }
  // ],
  // 关于面试:[
  //   {
  //     type:'autogenerated',
  //     dirName:'关于面试'
  //   }
  ]
};

'4a90f3f30f165e69c9dd6f3cd3c5ff61'.toUpperCase()
module.exports = sidebars;
